name: deploy-main
on: 
  push:
    branches:
      - main
jobs:
  deploy-main:
    runs-on: self-hosted
    steps:
      - run: bash -c "cd ~/cryptboard.io && git reset --hard && git pull && cd ./web-app && export HOME=/home/cryptboard && composer install"

